name: linuxserver-nginx
services:
  app:
    image: linuxserver/nginx:1.24.0
    restart: unless-stopped
    labels:
      icon: https://raw.githubusercontent.com/Ren96/CasaOS-Apps-Plus/main/Apps/nginx/icon.png
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 8080
        protocol: tcp
      - target: 443
        published: 8443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nginx/config
        target: /config

x-casaos:
  author: Ren
  category: Webhosting
  architectures:
    - amd64
    - arm
    - arm64
  tagline:
    en_us: 
  description:
    en_us: 
  project_url: 
  developer: 
    icon: https://raw.githubusercontent.com/Ren96/CasaOS-Apps-Plus/main/Apps/nginx/icon.png
  screenshot_link:

  port_map: "8080"

  scheme: http

  title:
    en_us: Nginx
