name: Crafty Controller
services:
  crafty-controller:
    container_name: craftycontroller 
    environment:
      - TZ=Etc/UTC
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    labels:
      icon: https://github.com/Ren96/CasaOS-Apps-Plus/blob/cbae4678f39d7e8e6af542fc7c37984fd2d4d773/Apps/craftycontrol/icon.png
    ports:
      - target: 8000
        published: "8080"
        protocol: tcp
      - target: 8443
        published: "8443"
        protocol: tcp
      - target: 8123
        published: "8123"
        protocol: tcp
      - target: 19132
        published: "19132"
        protocol: udp
      - target: 25565
        published: "25565"
        protocol: tcp
    privileged: false
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Crafty/docker/backups
        target: /crafty/backups
      - type: bind
        source: /DATA/AppData/Crafty/docker/logs
        target: /crafty/logs
      - type: bind
        source: /DATA/AppData/Crafty/docker/servers
        target: /crafty/servers
      - type: bind
        source: /DATA/AppData/Crafty/config
        target: /crafty/app/config
      - type: bind
        source: /DATA/AppData/Crafty/docker/import
        target: /crafty/import
    network_mode: bridge
x-casaos:
  author: Ren
  category: Apps+
  tagline:
    en_us: Take Control Of Your Servers
  project_url: https://gitlab.com/crafty-controller/crafty-4
  developer: Arcadia Technology
  icon: https://github.com/Ren96/CasaOS-Apps-Plus/blob/cbae4678f39d7e8e6af542fc7c37984fd2d4d773/Apps/craftycontrol/icon.png
  port_map: "8443"
  scheme: https
  title:
    en_us: Crafty Controller 
