name: Apache
services:
  httpd:
    container_name: apache

    image: httpd:latest

    labels:
      icon: https://raw.githubusercontent.com/Ren96/CasaOS-Apps-Plus/main/Apps/apache/icon.png

    ports:
      - target: 80
        published: "8080"
        protocol: tcp

    privileged: false
    restart: unless-stopped

    volumes:

      - type: bind
        source: /DATA/AppData/apache
        target: /app


    network_mode: bridge

x-casaos:
  author: Ren
  category: Webhosting
  architectures:
    - amd64
    - arm
    - arm64
  tagline:
    en_us: Flame is self-hosted startpage for your server with built-in apps and bookmarks editors. 
  description:
    en_us: Flame is self-hosted startpage for your server. Its design is inspired (heavily) by SUI. Flame is very easy to setup and use. With built-in editors, it allows you to setup your very own application hub in no time - no file editing necessary.
  project_url: https://github.com/pawelmalak/flame/
  developer: pawelmalak
  icon: https://raw.githubusercontent.com/Ren96/CasaOS-Apps-Plus/main/Apps/flame/icon.png
  screenshot_link:
  - https://raw.githubusercontent.com/Ren96/CasaOS-Apps-Plus/main/Apps/flame/screenshot-1.png
  - https://raw.githubusercontent.com/Ren96/CasaOS-Apps-Plus/main/Apps/flame/screenshot-2.png
  - https://raw.githubusercontent.com/Ren96/CasaOS-Apps-Plus/main/Apps/flame/screenshot-3.png
  - https://raw.githubusercontent.com/Ren96/CasaOS-Apps-Plus/main/Apps/flame/screenshot-4.png
  

  thumbnail: https://raw.githubusercontent.com/Ren96/CasaOS-Apps-Plus/main/Apps/flame/thumbnail.png

  port_map: "8080"
  scheme: http

  title:
    en_us: Apache
